Set FS = CreateObject("Scripting.FileSystemObject")

'steam游戏文件夹重命名操作
FS.DeleteFolder("D:\steamapps\steamapps")
FS.MoveFolder "D:\steamapps\steamapps_tran", "D:\steamapps\steamapps"

FS.DeleteFolder("D:\EpicGames")
FS.MoveFolder "D:\EpicGames_tran", "D:\EpicGames"

FS.DeleteFolder("D:\origin games")
FS.MoveFolder "D:\origin games_tran", "D:\origin games"

Set objShell = CreateObject("Wscript.Shell")
objShell.Run"""C:\Program Files (x86)\Netease\UUNetBar\uu_netbar.exe && mklink /J 'D:\Epic Games\GTAV\update' 'D:\steamapps\steamapps\common\Grand Theft Auto V\update' && mklink /J 'D:\Epic Games\GTAV\x64' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64' && mklink /h 'D:\Epic Games\GTAV\x64a.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64a.rpf' && mklink /h 'D:\Epic Games\GTAV\x64b.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64b.rpf' && mklink /h 'D:\Epic Games\GTAV\x64c.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64c.rpf' && mklink /h 'D:\Epic Games\GTAV\x64d.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64d.rpf' && mklink /h 'D:\Epic Games\GTAV\x64e.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64e.rpf' && mklink /h 'D:\Epic Games\GTAV\x64f.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64f.rpf' && mklink /h 'D:\Epic Games\GTAV\x64g.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64g.rpf' && mklink /h 'D:\Epic Games\GTAV\x64h.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64h.rpf' && mklink /h 'D:\Epic Games\GTAV\x64i.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64i.rpf' && mklink /h 'D:\Epic Games\GTAV\x64j.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64j.rpf' && mklink /h 'D:\Epic Games\GTAV\x64k.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64k.rpf' && mklink /h 'D:\Epic Games\GTAV\x64l.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64l.rpf' && mklink /h 'D:\Epic Games\GTAV\x64m.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64m.rpf' && mklink /h 'D:\Epic Games\GTAV\x64n.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64n.rpf' && mklink /h 'D:\Epic Games\GTAV\x64o.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64o.rpf' && mklink /h 'D:\Epic Games\GTAV\x64p.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64p.rpf' && mklink /h 'D:\Epic Games\GTAV\x64q.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64q.rpf' && mklink /h 'D:\Epic Games\GTAV\x64r.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64r.rpf' && mklink /h 'D:\Epic Games\GTAV\x64s.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64s.rpf' && mklink /h 'D:\Epic Games\GTAV\x64t.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64t.rpf' && mklink /h 'D:\Epic Games\GTAV\x64u.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64u.rpf' && mklink /h 'D:\Epic Games\GTAV\x64v.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64v.rpf' && mklink /h 'D:\Epic Games\GTAV\x64w.rpf' 'D:\steamapps\steamapps\common\Grand Theft Auto V\x64w.rpf'"""
